server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: false
      bandcamp: false
      soundcloud: true
      twitch: false
      vimeo: false
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    youtubePlaylistLoadLimit: 0
    playerUpdateInterval: 5
    youtubeSearchEnabled: false
    soundcloudSearchEnabled: true
    gc-warnings: true

logging:
  file:
    path: ./logs/
  level:
    root: INFO
    lavalink: INFO

  logback:
    rollingpolicy:
      max-file-size: 25MB
      max-history: 7
